# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20151124_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_after',
            field=models.DateTimeField(blank=True, help_text='If set will be published after this point automatically', null=True),
        ),
    ]
