# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_article_publish_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='count',
            field=models.IntegerField(default=0, help_text='Total views'),
        ),
    ]
