# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 06:01
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20151114_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
