# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0019_article_publish_after'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderAdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads')),
                ('published', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=120, null=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Header Ads',
            },
        ),
        migrations.CreateModel(
            name='SideAdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads')),
                ('published', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=120, null=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Side Ads',
            },
        ),
    ]
