# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads')),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderAdImage',
            fields=[
                ('adimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertising.AdImage')),
            ],
            bases=('advertising.adimage',),
        ),
        migrations.CreateModel(
            name='SideAdImage',
            fields=[
                ('adimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertising.AdImage')),
            ],
            bases=('advertising.adimage',),
        ),
        migrations.CreateModel(
            name='TopAdImage',
            fields=[
                ('adimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertising.AdImage')),
            ],
            bases=('advertising.adimage',),
        ),
    ]
