# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_adimage_categories_squashed_0003_auto_20160224_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headeradimage',
            options={'verbose_name_plural': 'Header Ads'},
        ),
        migrations.AlterModelOptions(
            name='sideadimage',
            options={'verbose_name_plural': 'Side Ads'},
        ),
        migrations.AlterModelOptions(
            name='topadimage',
            options={'verbose_name_plural': 'Top Ads'},
        ),
    ]
