# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_adimage_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adimage',
            name='categories',
        ),
        migrations.AddField(
            model_name='adimage',
            name='caption',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adimage',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
