# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 19:21
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('month', '0002_auto_20160218_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, null=True, populate_from='name', unique=True, verbose_name='URL'),
        ),
    ]
