# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_article_publish_after'),
        ('month', '0003_theme_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='articles.Article')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='month.Theme')),
            ],
        ),
    ]
